<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicosTableSeeder extends Seeder
{
    public function run(): void
    {
        $medicos = [
            // Médico 1 - Cardiólogo (user_id: 7)
            [
                'user_id' => 7,
                'primer_nombre' => 'José',
                'segundo_nombre' => 'Rafael',
                'primer_apellido' => 'Hernández',
                'segundo_apellido' => 'López',
                'tipo_documento' => 'V',
                'numero_documento' => '12345678',
                'fecha_nac' => '1975-04-12',
                'estado_id' => 10,
                'ciudad_id' => 1,
                'municipio_id' => 1,
                'parroquia_id' => 8,
                'direccion_detallada' => 'Av. San Martín, Consultorio Médico El Rosal',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4121111111',
                'genero' => 'Masculino',
                'nro_colegiatura' => 'MPPS 45678',
                'formacion_academica' => 'Médico Cirujano - Universidad Central de Venezuela (UCV). Especialista en Cardiología - Hospital Universitario de Caracas',
                'experiencia_profesional' => '20 años de experiencia en cardiología clínica e intervencionista. Ex-jefe del servicio de cardiología del Hospital Universitario de Caracas',
                'status' => true,
            ],

            // Médico 2 - Pediatra (user_id: 8)
            [
                'user_id' => 8,
                'primer_nombre' => 'Carmen',
                'segundo_nombre' => 'Elena',
                'primer_apellido' => 'Ramírez',
                'segundo_apellido' => 'Torres',
                'tipo_documento' => 'V',
                'numero_documento' => '14567890',
                'fecha_nac' => '1982-08-20',
                'estado_id' => 15,
                'ciudad_id' => 5,
                'municipio_id' => 4,
                'parroquia_id' => 23,
                'direccion_detallada' => 'Centro Médico Petare, Piso 2, Consultorio 205',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4142222222',
                'genero' => 'Femenino',
                'nro_colegiatura' => 'MPPS 56789',
                'formacion_academica' => 'Médico Cirujano - Universidad de Los Andes (ULA). Especialista en Pediatría - Hospital de Niños J.M. de los Ríos',
                'experiencia_profesional' => '15 años atendiendo niños y adolescentes. Especializada en pediatría preventiva y desarrollo infantil',
                'status' => true,
            ],

            // Médico 3 - Ginecólogo (user_id: 9)
            [
                'user_id' => 9,
                'primer_nombre' => 'Miguel',
                'segundo_nombre' => 'Ángel',
                'primer_apellido' => 'Gutiérrez',
                'segundo_apellido' => 'Medina',
                'tipo_documento' => 'V',
                'numero_documento' => '16789012',
                'fecha_nac' => '1978-11-05',
                'estado_id' => 7,
                'ciudad_id' => 9,
                'municipio_id' => 8,
                'parroquia_id' => 47,
                'direccion_detallada' => 'Clínica Valencia, Torre Médica, Piso 4',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4243333333',
                'genero' => 'Masculino',
                'nro_colegiatura' => 'MPPS 67890',
                'formacion_academica' => 'Médico Cirujano - Universidad de Carabobo (UC). Especialista en Ginecología y Obstetricia - Maternidad Concepción Palacios',
                'experiencia_profesional' => '18 años en ginecología y obstetricia. Más de 2000 partos atendidos. Experto en embarazos de alto riesgo',
                'status' => true,
            ],

            // Médico 4 - Traumatólogo (user_id: 10)
            [
                'user_id' => 10,
                'primer_nombre' => 'Pedro',
                'segundo_nombre' => 'Luis',
                'primer_apellido' => 'Moreno',
                'segundo_apellido' => 'Castro',
                'tipo_documento' => 'V',
                'numero_documento' => '13456789',
                'fecha_nac' => '1980-02-14',
                'estado_id' => 24,
                'ciudad_id' => 6,
                'municipio_id' => 5,
                'parroquia_id' => 30,
                'direccion_detallada' => 'Hospital Clínico de Maracaibo, Consultorios Externos',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4264444444',
                'genero' => 'Masculino',
                'nro_colegiatura' => 'MPPS 78901',
                'formacion_academica' => 'Médico Cirujano - Universidad del Zulia (LUZ). Especialista en Traumatología y Ortopedia - Hospital Universitario de Maracaibo',
                'experiencia_profesional' => '16 años en traumatología. Especializado en cirugía de rodilla y hombro. Médico del equipo de fútbol local',
                'status' => true,
            ],

            // Médico 5 - Dermatólogo (user_id: 11)
            [
                'user_id' => 11,
                'primer_nombre' => 'Laura',
                'segundo_nombre' => 'Patricia',
                'primer_apellido' => 'Vargas',
                'segundo_apellido' => 'Rojas',
                'tipo_documento' => 'V',
                'numero_documento' => '19234567',
                'fecha_nac' => '1985-06-30',
                'estado_id' => 13,
                'ciudad_id' => 12,
                'municipio_id' => 11,
                'parroquia_id' => 58,
                'direccion_detallada' => 'Centro Médico Barquisimeto, Torre B, Piso 3',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4145555555',
                'genero' => 'Femenino',
                'nro_colegiatura' => 'MPPS 89012',
                'formacion_academica' => 'Médico Cirujano - Universidad Centroccidental Lisandro Alvarado (UCLA). Especialista en Dermatología - Hospital Universitario de Caracas',
                'experiencia_profesional' => '12 años en dermatología clínica y estética. Experta en tratamiento de acné, psoriasis y procedimientos láser',
                'status' => true,
            ],

            // Médico 6 - Oftalmólogo (user_id: 12)
            [
                'user_id' => 12,
                'primer_nombre' => 'Andrés',
                'segundo_nombre' => 'Felipe',
                'primer_apellido' => 'Mendoza',
                'segundo_apellido' => 'Suárez',
                'tipo_documento' => 'V',
                'numero_documento' => '15678901',
                'fecha_nac' => '1979-09-18',
                'estado_id' => 4,
                'ciudad_id' => 15,
                'municipio_id' => 13,
                'parroquia_id' => 68,
                'direccion_detallada' => 'Centro Oftalmológico Maracay, Av. Las Delicias',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4166666666',
                'genero' => 'Masculino',
                'nro_colegiatura' => 'MPPS 90123',
                'formacion_academica' => 'Médico Cirujano - Universidad de Carabobo (UC). Especialista en Oftalmología - Instituto de Cirugía Ocular',
                'experiencia_profesional' => '17 años en oftalmología. Especializado en cirugía de cataratas y corrección visual con láser',
                'status' => true,
            ],

            // Médico 7 - Neurólogo (user_id: 13)
            [
                'user_id' => 13,
                'primer_nombre' => 'Diana',
                'segundo_nombre' => 'Carolina',
                'primer_apellido' => 'Ortiz',
                'segundo_apellido' => 'Vega',
                'tipo_documento' => 'V',
                'numero_documento' => '17890234',
                'fecha_nac' => '1983-12-08',
                'estado_id' => 20,
                'ciudad_id' => 21,
                'municipio_id' => 17,
                'parroquia_id' => 74,
                'direccion_detallada' => 'Centro Médico San Cristóbal, Piso 5',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4147777777',
                'genero' => 'Femenino',
                'nro_colegiatura' => 'MPPS 01234',
                'formacion_academica' => 'Médico Cirujano - Universidad de Los Andes (ULA). Especialista en Neurología - Hospital Universitario de Los Andes',
                'experiencia_profesional' => '14 años en neurología clínica. Experta en epilepsia, migraña y enfermedades neurodegenerativas',
                'status' => true,
            ],

            // Médico 8 - Psiquiatra (user_id: 14)
            [
                'user_id' => 14,
                'primer_nombre' => 'Ricardo',
                'segundo_nombre' => 'Enrique',
                'primer_apellido' => 'Silva',
                'segundo_apellido' => 'Paredes',
                'tipo_documento' => 'V',
                'numero_documento' => '14901234',
                'fecha_nac' => '1981-03-25',
                'estado_id' => 10,
                'ciudad_id' => 1,
                'municipio_id' => 1,
                'parroquia_id' => 12,
                'direccion_detallada' => 'Consultorio Psiquiátrico La Vega, Av. Principal',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4128888888',
                'genero' => 'Masculino',
                'nro_colegiatura' => 'MPPS 12345',
                'formacion_academica' => 'Médico Cirujano - Universidad Central de Venezuela (UCV). Especialista en Psiquiatría - Hospital Psiquiátrico de Caracas',
                'experiencia_profesional' => '15 años en psiquiatría clínica. Especializado en trastornos de ansiedad, depresión y terapia cognitivo-conductual',
                'status' => true,
            ],

            // Médico 9 - Endocrinólogo (user_id: 15)
            [
                'user_id' => 15,
                'primer_nombre' => 'Gabriela',
                'segundo_nombre' => 'Sofía',
                'primer_apellido' => 'Navarro',
                'segundo_apellido' => 'Campos',
                'tipo_documento' => 'V',
                'numero_documento' => '18012345',
                'fecha_nac' => '1986-07-11',
                'estado_id' => 6,
                'ciudad_id' => 28,
                'municipio_id' => 21,
                'parroquia_id' => null,
                'direccion_detallada' => 'Centro Médico Caroní, Puerto Ordaz',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4149999999',
                'genero' => 'Femenino',
                'nro_colegiatura' => 'MPPS 23456',
                'formacion_academica' => 'Médico Cirujano - Universidad de Oriente (UDO). Especialista en Endocrinología - Hospital Universitario de Caracas',
                'experiencia_profesional' => '11 años en endocrinología. Experta en diabetes, tiroides y trastornos hormonales',
                'status' => true,
            ],

            // Médico 10 - Gastroenterólogo (user_id: 16)
            [
                'user_id' => 16,
                'primer_nombre' => 'Fernando',
                'segundo_nombre' => 'Javier',
                'primer_apellido' => 'Reyes',
                'segundo_apellido' => 'Molina',
                'tipo_documento' => 'V',
                'numero_documento' => '16123456',
                'fecha_nac' => '1977-10-22',
                'estado_id' => 2,
                'ciudad_id' => 19,
                'municipio_id' => 16,
                'parroquia_id' => null,
                'direccion_detallada' => 'Hospital Universitario de Puerto La Cruz, Consultorios',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4240000000',
                'genero' => 'Masculino',
                'nro_colegiatura' => 'MPPS 34567',
                'formacion_academica' => 'Médico Cirujano - Universidad de Oriente (UDO). Especialista en Gastroenterología - Hospital Vargas de Caracas',
                'experiencia_profesional' => '19 años en gastroenterología. Más de 5000 endoscopias realizadas. Experto en enfermedad inflamatoria intestinal',
                'status' => true,
            ],

            // Médico 11 - Medicina General (user_id: 17)
            [
                'user_id' => 17,
                'primer_nombre' => 'Valentina',
                'segundo_nombre' => 'Isabel',
                'primer_apellido' => 'Castillo',
                'segundo_apellido' => 'Ramos',
                'tipo_documento' => 'V',
                'numero_documento' => '21234567',
                'fecha_nac' => '1990-01-15',
                'estado_id' => 7,
                'ciudad_id' => 9,
                'municipio_id' => 9,
                'parroquia_id' => null,
                'direccion_detallada' => 'Ambulatorio Naguanagua, Av. Universidad',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4241111111',
                'genero' => 'Femenino',
                'nro_colegiatura' => 'MPPS 45670',
                'formacion_academica' => 'Médico Cirujano - Universidad de Carabobo (UC)',
                'experiencia_profesional' => '8 años en medicina general. Atención primaria en salud y medicina preventiva',
                'status' => true,
            ],

            // Médico 12 - Medicina Interna (user_id: 18)
            [
                'user_id' => 18,
                'primer_nombre' => 'Alejandro',
                'segundo_nombre' => 'David',
                'primer_apellido' => 'Flores',
                'segundo_apellido' => 'Guerrero',
                'tipo_documento' => 'V',
                'numero_documento' => '13789012',
                'fecha_nac' => '1976-05-28',
                'estado_id' => 14,
                'ciudad_id' => 24,
                'municipio_id' => 19,
                'parroquia_id' => null,
                'direccion_detallada' => 'Hospital Universitario de Los Andes, Mérida',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4142222220',
                'genero' => 'Masculino',
                'nro_colegiatura' => 'MPPS 56781',
                'formacion_academica' => 'Médico Cirujano - Universidad de Los Andes (ULA). Especialista en Medicina Interna - Hospital Universitario de Los Andes',
                'experiencia_profesional' => '21 años en medicina interna. Manejo de pacientes con enfermedades crónicas complejas y comorbilidades',
                'status' => true,
            ],
        ];

        foreach ($medicos as $medico) {
            DB::table('medicos')->insert(array_merge($medico, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
