<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PacientesTableSeeder extends Seeder
{
    public function run(): void
    {
        $pacientes = [
            // Paciente 1 (user_id: 19)
            [
                'user_id' => 19,
                'primer_nombre' => 'Juan',
                'segundo_nombre' => 'Carlos',
                'primer_apellido' => 'Pérez',
                'segundo_apellido' => 'González',
                'tipo_documento' => 'V',
                'numero_documento' => '20345678',
                'fecha_nac' => '1995-03-15',
                'estado_id' => 10,
                'ciudad_id' => 1,
                'municipio_id' => 1,
                'parroquia_id' => 14,
                'direccion_detallada' => 'Urb. El Valle, Calle 3, Casa 25',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4121234567',
                'genero' => 'Masculino',
                'ocupacion' => 'Ingeniero de Sistemas',
                'estado_civil' => 'Soltero',
                'status' => true,
            ],

            // Paciente 2 (user_id: 20)
            [
                'user_id' => 20,
                'primer_nombre' => 'María',
                'segundo_nombre' => 'José',
                'primer_apellido' => 'Rodríguez',
                'segundo_apellido' => 'Martínez',
                'tipo_documento' => 'V',
                'numero_documento' => '22456789',
                'fecha_nac' => '1988-07-22',
                'estado_id' => 15,
                'ciudad_id' => 5,
                'municipio_id' => 4,
                'parroquia_id' => 23,
                'direccion_detallada' => 'Petare, Sector La Bombilla, Edificio Los Pinos, Apto 5-A',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4142345678',
                'genero' => 'Femenino',
                'ocupacion' => 'Profesora',
                'estado_civil' => 'Casada',
                'status' => true,
            ],

            // Paciente 3 (user_id: 21)
            [
                'user_id' => 21,
                'primer_nombre' => 'Pedro',
                'segundo_nombre' => 'Antonio',
                'primer_apellido' => 'López',
                'segundo_apellido' => 'Fernández',
                'tipo_documento' => 'V',
                'numero_documento' => '18567890',
                'fecha_nac' => '1992-11-08',
                'estado_id' => 7,
                'ciudad_id' => 9,
                'municipio_id' => 8,
                'parroquia_id' => 48,
                'direccion_detallada' => 'Valencia, Urb. La Viña, Torre 2, Piso 8, Apto 8-B',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4243456789',
                'genero' => 'Masculino',
                'ocupacion' => 'Contador',
                'estado_civil' => 'Soltero',
                'status' => true,
            ],

            // Paciente 4 (user_id: 22)
            [
                'user_id' => 22,
                'primer_nombre' => 'Ana',
                'segundo_nombre' => 'Luisa',
                'primer_apellido' => 'García',
                'segundo_apellido' => 'Ramírez',
                'tipo_documento' => 'V',
                'numero_documento' => '25678901',
                'fecha_nac' => '1998-05-30',
                'estado_id' => 24,
                'ciudad_id' => 6,
                'municipio_id' => 5,
                'parroquia_id' => 31,
                'direccion_detallada' => 'Maracaibo, Av. Bella Vista, Residencias Don Pedro',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4264567890',
                'genero' => 'Femenino',
                'ocupacion' => 'Diseñadora Gráfica',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],

            // Paciente 5 (user_id: 23)
            [
                'user_id' => 23,
                'primer_nombre' => 'Luis',
                'segundo_nombre' => 'Fernando',
                'primer_apellido' => 'Sánchez',
                'segundo_apellido' => 'Morales',
                'tipo_documento' => 'V',
                'numero_documento' => '16789012',
                'fecha_nac' => '1985-09-12',
                'estado_id' => 13,
                'ciudad_id' => 12,
                'municipio_id' => 11,
                'parroquia_id' => 60,
                'direccion_detallada' => 'Barquisimeto, Urb. Nueva Segovia, Calle 15',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4145678901',
                'genero' => 'Masculino',
                'ocupacion' => 'Abogado',
                'estado_civil' => 'Casado',
                'status' => true,
            ],

            // Paciente 6 (user_id: 24)
            [
                'user_id' => 24,
                'primer_nombre' => 'Carmen',
                'segundo_nombre' => 'Victoria',
                'primer_apellido' => 'Díaz',
                'segundo_apellido' => 'Silva',
                'tipo_documento' => 'V',
                'numero_documento' => '21890123',
                'fecha_nac' => '1993-02-18',
                'estado_id' => 4,
                'ciudad_id' => 15,
                'municipio_id' => 13,
                'parroquia_id' => 69,
                'direccion_detallada' => 'Maracay, Urb. El Castaño, Calle Los Samanes',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4166789012',
                'genero' => 'Femenino',
                'ocupacion' => 'Enfermera',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],

            // Paciente 7 (user_id: 25)
            [
                'user_id' => 25,
                'primer_nombre' => 'Roberto',
                'segundo_nombre' => 'José',
                'primer_apellido' => 'Hernández',
                'segundo_apellido' => 'Castro',
                'tipo_documento' => 'V',
                'numero_documento' => '14901234',
                'fecha_nac' => '1980-12-25',
                'estado_id' => 20,
                'ciudad_id' => 21,
                'municipio_id' => 17,
                'parroquia_id' => 76,
                'direccion_detallada' => 'San Cristóbal, Barrio Obrero, Calle 7',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4147890123',
                'genero' => 'Masculino',
                'ocupacion' => 'Comerciante',
                'estado_civil' => 'Divorciado',
                'status' => true,
            ],

            // Paciente 8 (user_id: 26)
            [
                'user_id' => 26,
                'primer_nombre' => 'Gabriela',
                'segundo_nombre' => 'Alejandra',
                'primer_apellido' => 'Vargas',
                'segundo_apellido' => 'Mendoza',
                'tipo_documento' => 'V',
                'numero_documento' => '23012345',
                'fecha_nac' => '1996-06-14',
                'estado_id' => 6,
                'ciudad_id' => 28,
                'municipio_id' => 21,
                'parroquia_id' => null,
                'direccion_detallada' => 'Puerto Ordaz, Urb. Villa Asia, Torre 5',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4148901234',
                'genero' => 'Femenino',
                'ocupacion' => 'Psicóloga',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],

            // Paciente 9 (user_id: 27)
            [
                'user_id' => 27,
                'primer_nombre' => 'Miguel',
                'segundo_nombre' => 'Eduardo',
                'primer_apellido' => 'Torres',
                'segundo_apellido' => 'Reyes',
                'tipo_documento' => 'V',
                'numero_documento' => '19123456',
                'fecha_nac' => '1991-08-20',
                'estado_id' => 2,
                'ciudad_id' => 19,
                'municipio_id' => 16,
                'parroquia_id' => null,
                'direccion_detallada' => 'Puerto La Cruz, Urb. Lechería, Calle Principal',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4249012345',
                'genero' => 'Masculino',
                'ocupacion' => 'Arquitecto',
                'estado_civil' => 'Casado',
                'status' => true,
            ],

            // Paciente 10 (user_id: 28)
            [
                'user_id' => 28,
                'primer_nombre' => 'Daniela',
                'segundo_nombre' => 'Sofía',
                'primer_apellido' => 'Moreno',
                'segundo_apellido' => 'Ortiz',
                'tipo_documento' => 'V',
                'numero_documento' => '24234567',
                'fecha_nac' => '1999-04-05',
                'estado_id' => 10,
                'ciudad_id' => 1,
                'municipio_id' => 1,
                'parroquia_id' => 9,
                'direccion_detallada' => 'El Paraíso, Av. Principal, Edificio Paraíso, Apto 12-C',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4120123456',
                'genero' => 'Femenino',
                'ocupacion' => 'Estudiante Universitaria',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],

            // Paciente 11 (user_id: 29)
            [
                'user_id' => 29,
                'primer_nombre' => 'Carlos',
                'segundo_nombre' => 'Andrés',
                'primer_apellido' => 'Navarro',
                'segundo_apellido' => 'Gutiérrez',
                'tipo_documento' => 'V',
                'numero_documento' => '17345678',
                'fecha_nac' => '1987-10-11',
                'estado_id' => 14,
                'ciudad_id' => 24,
                'municipio_id' => 19,
                'parroquia_id' => null,
                'direccion_detallada' => 'Mérida, Av. Las Américas, Residencias Los Andes',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4141234567',
                'genero' => 'Masculino',
                'ocupacion' => 'Médico Veterinario',
                'estado_civil' => 'Casado',
                'status' => true,
            ],

            // Paciente 12 (user_id: 30)
            [
                'user_id' => 30,
                'primer_nombre' => 'Patricia',
                'segundo_nombre' => 'Isabel',
                'primer_apellido' => 'Castillo',
                'segundo_apellido' => 'Vega',
                'tipo_documento' => 'V',
                'numero_documento' => '20456789',
                'fecha_nac' => '1994-01-28',
                'estado_id' => 7,
                'ciudad_id' => 9,
                'municipio_id' => 10,
                'parroquia_id' => null,
                'direccion_detallada' => 'San Diego, Urb. Valles de Camoruco, Casa 45',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4242345678',
                'genero' => 'Femenino',
                'ocupacion' => 'Administradora',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],

            // Paciente 13 (user_id: 31)
            [
                'user_id' => 31,
                'primer_nombre' => 'Javier',
                'segundo_nombre' => 'Alejandro',
                'primer_apellido' => 'Ramos',
                'segundo_apellido' => 'Flores',
                'tipo_documento' => 'V',
                'numero_documento' => '15567890',
                'fecha_nac' => '1983-07-03',
                'estado_id' => 15,
                'ciudad_id' => 3,
                'municipio_id' => 3,
                'parroquia_id' => null,
                'direccion_detallada' => 'Guarenas, Urb. Nueva Casarapa, Calle 8',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4143456789',
                'genero' => 'Masculino',
                'ocupacion' => 'Electricista',
                'estado_civil' => 'Casado',
                'status' => true,
            ],

            // Paciente 14 (user_id: 32)
            [
                'user_id' => 32,
                'primer_nombre' => 'Valentina',
                'segundo_nombre' => 'María',
                'primer_apellido' => 'Suárez',
                'segundo_apellido' => 'Paredes',
                'tipo_documento' => 'V',
                'numero_documento' => '26678901',
                'fecha_nac' => '2000-11-19',
                'estado_id' => 24,
                'ciudad_id' => 6,
                'municipio_id' => 6,
                'parroquia_id' => null,
                'direccion_detallada' => 'San Francisco, Urb. Los Olivos, Casa 78',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4264567891',
                'genero' => 'Femenino',
                'ocupacion' => 'Estudiante',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],

            // Paciente 15 (user_id: 33)
            [
                'user_id' => 33,
                'primer_nombre' => 'Andrés',
                'segundo_nombre' => 'Manuel',
                'primer_apellido' => 'Medina',
                'segundo_apellido' => 'Campos',
                'tipo_documento' => 'V',
                'numero_documento' => '13789012',
                'fecha_nac' => '1978-03-07',
                'estado_id' => 13,
                'ciudad_id' => 13,
                'municipio_id' => 12,
                'parroquia_id' => null,
                'direccion_detallada' => 'Cabudare, Urb. La Piedad, Calle 12',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4145678902',
                'genero' => 'Masculino',
                'ocupacion' => 'Mecánico',
                'estado_civil' => 'Divorciado',
                'status' => true,
            ],

            // Paciente 16 (user_id: 34)
            [
                'user_id' => 34,
                'primer_nombre' => 'Isabella',
                'segundo_nombre' => 'Carolina',
                'primer_apellido' => 'Rojas',
                'segundo_apellido' => 'Guerrero',
                'tipo_documento' => 'V',
                'numero_documento' => '22890123',
                'fecha_nac' => '1997-09-23',
                'estado_id' => 4,
                'ciudad_id' => 16,
                'municipio_id' => 14,
                'parroquia_id' => null,
                'direccion_detallada' => 'Turmero, Centro, Calle Comercio',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4166789013',
                'genero' => 'Femenino',
                'ocupacion' => 'Farmacéutica',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],

            // Paciente 17 (user_id: 35)
            [
                'user_id' => 35,
                'primer_nombre' => 'Diego',
                'segundo_nombre' => 'Alberto',
                'primer_apellido' => 'Molina',
                'segundo_apellido' => 'Acosta',
                'tipo_documento' => 'V',
                'numero_documento' => '18901234',
                'fecha_nac' => '1990-12-16',
                'estado_id' => 10,
                'ciudad_id' => 1,
                'municipio_id' => 1,
                'parroquia_id' => 19,
                'direccion_detallada' => 'Catia, Sector Nuevo Horizonte, Calle 5',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4127890124',
                'genero' => 'Masculino',
                'ocupacion' => 'Chofer',
                'estado_civil' => 'Casado',
                'status' => true,
            ],

            // Paciente 18 (user_id: 36)
            [
                'user_id' => 36,
                'primer_nombre' => 'Camila',
                'segundo_nombre' => 'Andrea',
                'primer_apellido' => 'Peña',
                'segundo_apellido' => 'Salazar',
                'tipo_documento' => 'V',
                'numero_documento' => '25012345',
                'fecha_nac' => '2001-05-09',
                'estado_id' => 6,
                'ciudad_id' => 27,
                'municipio_id' => 20,
                'parroquia_id' => null,
                'direccion_detallada' => 'Ciudad Bolívar, Av. Germania, Edificio Centro',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4148901235',
                'genero' => 'Femenino',
                'ocupacion' => 'Estudiante',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],

            // Paciente 19 (user_id: 37)
            [
                'user_id' => 37,
                'primer_nombre' => 'Santiago',
                'segundo_nombre' => 'Rafael',
                'primer_apellido' => 'Blanco',
                'segundo_apellido' => 'Núñez',
                'tipo_documento' => 'V',
                'numero_documento' => '16234567',
                'fecha_nac' => '1986-02-27',
                'estado_id' => 2,
                'ciudad_id' => 18,
                'municipio_id' => 15,
                'parroquia_id' => null,
                'direccion_detallada' => 'Barcelona, Urb. Nueva Barcelona, Calle 10',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4249012346',
                'genero' => 'Masculino',
                'ocupacion' => 'Ingeniero Civil',
                'estado_civil' => 'Casado',
                'status' => true,
            ],

            // Paciente 20 (user_id: 38)
            [
                'user_id' => 38,
                'primer_nombre' => 'Sofía',
                'segundo_nombre' => 'Valentina',
                'primer_apellido' => 'Cruz',
                'segundo_apellido' => 'Herrera',
                'tipo_documento' => 'V',
                'numero_documento' => '21345678',
                'fecha_nac' => '1995-08-31',
                'estado_id' => 7,
                'ciudad_id' => 9,
                'municipio_id' => 8,
                'parroquia_id' => 49,
                'direccion_detallada' => 'Valencia, Urb. Trigal Norte, Torre 3, Piso 6',
                'prefijo_tlf' => '+58',
                'numero_tlf' => '4240123457',
                'genero' => 'Femenino',
                'ocupacion' => 'Odontóloga',
                'estado_civil' => 'Soltera',
                'status' => true,
            ],
        ];

        foreach ($pacientes as $paciente) {
            DB::table('pacientes')->insert(array_merge($paciente, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
        $now = now();
        $pacientes = [];

        // 1. Pacientes (IDs 8-10)
        // Paciente 1 (ID 8)
        $pacientes[] = [
            'user_id' => 8,
            'primer_nombre' => 'José',
            'primer_apellido' => 'Méndez',
            'tipo_documento' => 'V',
            'numero_documento' => '21000008',
            'fecha_nac' => '1995-02-14',
            'estado_id' => 1,
            'ciudad_id' => 1,
            'municipio_id' => 1,
            'parroquia_id' => 1,
            'direccion_detallada' => 'Barrio 5 de Julio',
            'prefijo_tlf' => '+58',
            'numero_tlf' => '4240000008',
            'genero' => 'Masculino',
            'ocupacion' => 'Estudiante',
            'estado_civil' => 'Soltero',
            'status' => true,
            'created_at' => $now,
            'updated_at' => $now,
        ];

        // Paciente 2 (ID 9)
        $pacientes[] = [
            'user_id' => 9,
            'primer_nombre' => 'Carmen',
            'primer_apellido' => 'Ortiz',
            'tipo_documento' => 'V',
            'numero_documento' => '22000009',
            'fecha_nac' => '1960-09-30',
            'estado_id' => 1,
            'ciudad_id' => 1,
            'municipio_id' => 1,
            'parroquia_id' => 1,
            'direccion_detallada' => 'Residencias Los Andes',
            'prefijo_tlf' => '+58',
            'numero_tlf' => '4160000009',
            'genero' => 'Femenino',
            'ocupacion' => 'Jubilada',
            'estado_civil' => 'Viuda',
            'status' => true,
            'created_at' => $now,
            'updated_at' => $now,
        ];

        // Paciente 3 (ID 10)
        $pacientes[] = [
            'user_id' => 10,
            'primer_nombre' => 'Luis',
            'primer_apellido' => 'Silva',
            'tipo_documento' => 'V',
            'numero_documento' => '23000010',
            'fecha_nac' => '2010-06-01',
            'estado_id' => 1,
            'ciudad_id' => 1,
            'municipio_id' => 1,
            'parroquia_id' => 1,
            'direccion_detallada' => 'Urbanización del Este',
            'prefijo_tlf' => '+58',
            'numero_tlf' => '4120000010',
            'genero' => 'Masculino',
            'ocupacion' => 'Estudiante',
            'estado_civil' => 'Soltero',
            'status' => true,
            'created_at' => $now,
            'updated_at' => $now,
        ];

        DB::table('pacientes')->insert($pacientes);
    }
}
